# QPunishments config
# This config is updated for QPunishments ${project.version}

announcements:
  punishments:
    ban: true
    mute: true
    kick: true

staff-chat:
  enabled: true
  chat-char: '@'

# Commands which are blocked while muted
blocked-commands:
  - r
  - tell
  - whisper
  - msg

# Commands which are always blocked
blocked-commands-bypass-permission: "qpunishments.bypass.commandblock"
general-blocked-commands:
  - plugins
  - pl
  - bukkit:plugins
  - bukkit:pl
  - about
  - ?

sqlite:
  enabled: false

# MySQL is the default because there is no default SQLite driver for BungeeCord, an external driver needs to be downloaded
mysql:
  enabled: true
  host:
  port: 3306
  database: qpunishments
  user:
  pass:
  ssl: false

redis:
  enabled: false
  host:
  port: 6379
  pass: